### ISSUE TITLE
Home folder hardcoded in the premade executable

### ISSUE THREAD

**Issue by kosonya** [NSchrading/redditDataExtractor#12]
I tried downloading the premade executable for Linux, and I'm getting the following error when trying to run it:
` /exe.linux-x86_64-3.4$ ./redditDataExtractor 
/mnt/plaintext_data/Downloads/ubuntu/exe.linux-x86_64-3.4/library.zip/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "/home/jschradi/anaconda3/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "main.py", line 125, in <module>
  File "main.py", line 89, in main
  File "main.py", line 84, in loadState
  File "/home/jschradi/anaconda3/lib/python3.4/shelve.py", line 141, in close
  File "/home/jschradi/anaconda3/lib/python3.4/shelve.py", line 168, in sync
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 113, in _commit
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 257, in _chmod
PermissionError: [Errno 1] Operation not permitted: 'RedditDataExtractor/saves/settings.db.dir'
Exception ignored in: <bound method DbfilenameShelf.__del__ of <shelve.DbfilenameShelf object at 0x7fc0433c92b0>>
Traceback (most recent call last):
  File "/home/jschradi/anaconda3/lib/python3.4/shelve.py", line 158, in __del__
  File "/home/jschradi/anaconda3/lib/python3.4/shelve.py", line 141, in close
  File "/home/jschradi/anaconda3/lib/python3.4/shelve.py", line 168, in sync
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 113, in _commit
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 257, in _chmod
PermissionError: [Errno 1] Operation not permitted: 'RedditDataExtractor/saves/settings.db.dir'
Exception ignored in: <bound method _Database.close of <dbm.dumb._Database object at 0x7fc0433c92e8>>
Traceback (most recent call last):
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 250, in close
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 113, in _commit
  File "/home/jschradi/anaconda3/lib/python3.4/dbm/dumb.py", line 257, in _chmod
PermissionError: [Errno 1] Operation not permitted: 'RedditDataExtractor/saves/settings.db.dir'
`
Looks like a bunch of paths are hardcoded, and don't get ported to a different system.

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
