### ISSUE TITLE
pre-made Linux executable crashes probably because a hardcoded home folder

### ISSUE THREAD

**Issue by informer2016** [NSchrading/redditDataExtractor#13]
@NSchrading , that's probably related to #12 . Trying to launch the pre-made Linux executable and it crashes:
~~~
exe.linux-x86_64-3.4$ /home/myusername/rde/exe.linux-x86_64-3.4/library.zip/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "/home/jschradi/anaconda3/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "main.py", line 24, in <module>
ImportError: cannot import name 'QApplication'

[5]-  Exit 1                  ./redditDataExtractor
~~~

**Comment by tdeck** [comment]
Having the same issue today.

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
